version: 2

models:
  - name: daily_report
    columns:
      - name: visits
        tests:
          - not_null

      - name: pageviews
        tests:
          - not_null

  - name: user_stats
    columns:
      - name: visitorId
        tests: 
          - not_null 
      - name: date
        tests: 
          - last_date
